### ISSUE TITLE
Add automatic tests and GitHub CI file

### ISSUE THREAD

**Issue by sypets** [ElementareTeilchen/unduplicator#8]
I can work on this but would like some feedback if extension still maintained and further work is encouraged. Thank you!

**Comment by franzkugelmann** [comment]
@sypets absolutely! Thank you very much for your contributions so far! I did not find the time so far to closely review and test your contributions myself with an v11 instance, because we have no explicit need currently.

**Comment by sypets** [comment]
Closing this. There are tests and .github workflows.
